spring:
  application:
    name: cloud-demo-provider
    
server:
  port: 3333
  
eureka:
  client: 
    registryFetchIntervalSeconds: 10 
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    
feign:
  hystrix:
    enabled: true
  httpclient: 
    connectionTimeout: 1000
    maxConnectionsPerRoute: 2
    maxConnections: 10