mybatis:
  mapper-locations: mybatis/*.xml
  configuration:
    default-statement-timeout: 5

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: wadzxqes7
  application:
    name: cloud-demo-provider

server:
  port: 8080

eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

feign:
  hystrix:
    enabled: true
  httpclient:
    connectionTimeout: 1000
    maxConnectionsPerRoute: 2
    maxConnections: 10

suixingpay:
  swagger2:
    title: sms
    description: sms
    contact:
      name: matieli
      url: http://vbill.cn
      email: ma_tl@suixingpay.com
    # swagger 需要扫的包
    base-package: com.springboot.app
    base-path: /**
    exclude-path: /error, ${management.context-path}/**