spring:
  application:
    name: cloud-demo-registry
    
server:
  port: 1111
  
eureka:
  server: 
    evictionIntervalTimerInMs: 60000
    
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka